ALTER TABLE exams DROP CONSTRAINT IF EXISTS exams_room_id_fkey;
ALTER TABLE exams DROP COLUMN IF EXISTS room_id;
ALTER TABLE exams ADD COLUMN room_number VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE exams ALTER COLUMN room_number DROP DEFAULT;
